---
sidebar: sidebar
permalink: task-s3-enable-data-services.html
keywords: s3 buckets, s3 storage, s3 working environment, amazon s3 buckets, amazon s3 working environment
summary: After you discover S3 buckets in BlueXP, you can use NetApp data services for backup, tiering, classification, and data synchronization.
---

= Use NetApp data services with S3 buckets
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you discover S3 buckets in BlueXP, you can use NetApp data services for backup, tiering, classification, and data synchronization.

* Use *BlueXP backup and recovery* to back up data from your on-premises ONTAP and Cloud Volumes ONTAP systems to S3 object storage.
+
To get started, go to the Canvas and drag and drop an on-premises ONTAP or Cloud Volumes ONTAP working environment on your Amazon S3 working environment.
+
https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html[Learn more about backing up ONTAP data to Amazon S3 storage^].

* Use *BlueXP tiering* to tier inactive data from on-premises ONTAP clusters to S3 object storage.
+
To get started, go to the Canvas and drag and drop an on-premises ONTAP working environment on your Amazon S3 working environment.
+
https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-aws.html[Learn more about tiering ONTAP data to Amazon S3 storage^].

* Use *BlueXP copy and sync* to synchronize data to or from S3 buckets.
+
To get started, go to the Canvas and drag and drop the source working environment on the target working environment. Your Amazon S3 working environment can be either the source or target. 
+
You can also select your Amazon S3 working environment and click *Copy & sync* from the Services panel to synchronize data to or from S3 buckets.
+
https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html[Learn more about the BlueXP copy and sync service^].

* Use *BlueXP classification* to scan your S3 buckets for personal and sensitive data. BlueXP classification can scan any bucket in the account, regardless of whether it was created for a NetApp solution.
+
To get started, select your Amazon S3 working environment and select the appropriate option from the *Classification* section of the Services panel to initiate scanning of your S3 buckets.
+
https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-s3.html[Learn more about the BlueXP classification service^].